### ISSUE TITLE
python3如何调用？

### ISSUE THREAD

**Issue by feature09** [percipioxyz/camport3#1]
请问我想使用python-opencv去调用摄像头该如何调用呢？
是FM830-5M。

正常我只需要索引0号的摄像头就可以连接到摄像头了。

```
def demo():
	capture = cv2.VideoCapture(0)
	if capture.isOpened():
		while True:
			ret, frame = capture.read()
			cv2.imshow("camera",frame)
			if cv2.waitKey(30) & 0xff == 27:
				capture.release()
				break
	else:
		print("未检测到摄像头")
demo()
cv2.waitKey()
cv2.destroyAllWindows()
```

可是用USB连上摄像头之后，仍旧是检测到我的笔记本摄像头。
我用其他的USB摄像头(M)连接的话，就是显示M摄像头的内容。

**Comment by feature09** [comment]
在Ubuntu系统上，上述代码就没有问题了，在Windows10上就不行。

**Comment by berylyellow** [comment]
> 在Ubuntu系统上，上述代码就没有问题了，在Windows10上就不行。

请问你问题怎么解决的？用python调用显示：
VIDEOIO ERROR: V4L2: Could not obtain specifics of capture window.
VIDEOIO ERROR: V4L: can't open camera by index 1
